### ISSUE TITLE
handle decorated constructors (use the .__wrapped__ constructor)

### ISSUE THREAD

**Issue by citrusmunch** [lucsorel/py2puml#24]
Hello, I'm getting an `AttributeError` and I don't quite know how to fix the traversed code.

### Issue

`py2puml` works great, but I'm trying to use it to clean up a *very* imperfect codebase and I've had to make some adjustments to the codebase for successful `py2puml` output (which is fine). I don't know what I need to adjust to fix the current error though.

running `py2puml manim/mobject manim.mobject` on `manim`@[c69f6eb](https://github.com/ManimCommunity/manim/commit/c69f6eb3e3b2bba1351471f06d1b2a0014df54e6) yields:

<details><summary>Traceback</summary>
<p>

```logTraceback (most recent call last):
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/bin/py2puml", line 8, in <module>
    sys.exit(run())
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/cli.py", line 17, in run
    print(''.join(py2puml(args.path, args.module)))
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/py2puml.py", line 18, in py2puml
    inspect_module(
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/inspection/inspectmodule.py", line 59, in inspect_module
    inspect_domain_definition(definition_type, root_module_name, domain_items_by_fqn, domain_relations)
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/inspection/inspectmodule.py", line 46, in inspect_domain_definition
    inspect_class_type(
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/inspection/inspectclass.py", line 97, in inspect_class_type
    instance_attributes, compositions = parse_class_constructor(class_type, class_type_fqn, root_module_name)
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/parsing/parseclassconstructor.py", line 39, in parse_class_constructor
    visitor.visit(constructor_ast)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/parsing/astvisitors.py", line 98, in generic_visit
    NodeVisitor.generic_visit(self, node)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/parsing/astvisitors.py", line 108, in visit_FunctionDef
    self.generic_visit(node)
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/parsing/astvisitors.py", line 98, in generic_visit
    NodeVisitor.generic_visit(self, node)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/parsing/astvisitors.py", line 98, in generic_visit
    NodeVisitor.generic_visit(self, node)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/citrus/Library/Caches/pypoetry/virtualenvs/manim-fDwhioqp-py3.9/lib/python3.9/site-packages/py2puml/parsing/astvisitors.py", line 126, in visit_Assign
    variables_collector = AssignedVariablesCollector(self.class_self_id, None)
AttributeError: 'ConstructorVisitor' object has no attribute 'class_self_id'
```

</p>
</details>

### Success

I have success with 
- `py2puml manim/mobjects/svg manim.mobjects.svg`
  after deleting `manim/mobject/svg/opengl_tex_mobject.py` and `manim/mobject/svg/opengl_text_mobject.py`
- `py2puml manim/mobject/types manim.mobject.types`

so maybe that narrows the issue down slightly 😅.

**Comment by citrusmunch** [comment]
I ended up walking through with `pdb` and found the culprit!
Commenting out the class definitions for `FullScreenFadeRectangle` and `PictureInPictureFrame` from `manim/mobject/frame.py` resolves this particular error.
It's not clear to me why those classes are problematic though. I'll leave this issue up for a bit in case there's an obvious answer we can document, but otherwise my problem is solved.

There's a bit more I had to clean up but I have everything working!

**Comment by lucsorel** [comment]
hi @citrusmunch 

I investigated this issue and it comes from the parsing of `manim.mobject.frame.FullScreenFadeRectangle`'s contructor. It is a class decorated by the `@deprecated` decorator.

When py2puml parses its constructor, it actually parses the decorated one:

```python
def fun(*args, **kw):
    if not kwsyntax:
        args, kw = fix(args, kw, sig)
    return caller(func, *(extras + args), **kw)
```

Instead of the original one:

```python
def __init__(self, stroke_width=0, fill_color=BLACK, fill_opacity=0.7, **kwargs):
    super().__init__(
        stroke_width=stroke_width,
        fill_color=fill_color,
        fill_opacity=fill_opacity,
        **kwargs
    )
```

I have to find a way to figure out how to detect decorated constructors and how to access to the code of the real constructor. Not easy...

**Comment by citrusmunch** [comment]
This is good to know, thanks! Not easy indeed...

**Comment by lucsorel** [comment]
Ok, I found a fix by inserting this instruction at line 35 of `py2puml/parsing/parseclassconstructor.py` (you can apply this fix in your virtual environment):

```python
constructor = getattr(constructor, '__wrapped__', constructor)
```

But then another error pops up:

```text
Traceback (most recent call last):
  File ".../manim/.venv/bin/py2puml", line 8, in <module>
    sys.exit(run())
  File ".../manim/.venv/lib/python3.8/site-packages/py2puml/cli.py", line 17, in run
    print(''.join(py2puml(args.path, args.module)))
  File ".../manim/.venv/lib/python3.8/site-packages/py2puml/py2puml.py", line 17, in py2puml
    domain_item_module: ModuleType = import_module(name)
  File "/home/luc/.pyenv/versions/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../manim/manim/mobject/svg/opengl_tex_mobject.py", line 175, in <module>
    from ...mobject.svg.opengl_svg_mobject import OpenGLSVGMobject
ModuleNotFoundError: No module named 'manim.mobject.svg.opengl_svg_mobject'
```

And indeed, there are incorrect imports in [`manim/mobject/svg/opengl_tex_mobject.py` lines 175-176](https://github.com/ManimCommunity/manim/blob/c69f6eb3e3b2bba1351471f06d1b2a0014df54e6/manim/mobject/svg/opengl_tex_mobject.py#L175-L176):

```python
from ...mobject.svg.opengl_svg_mobject import OpenGLSVGMobject
from ...mobject.svg.opengl_svg_path import OpenGLSVGPathMobject
```

Neither `opengl_svg_mobject` nor `opengl_svg_path` modules exist :thinking:

**Comment by lucsorel** [comment]
better fix (there can be a chain of decorators, leading to a chain of `__wrapped__.__wrapped__...__wrapped__`):

```python
from inspect import unwrap
constructor = unwrap(constructor)
```
